import Head from "next/head";
import Image from "next/image";
import styles from "../styles/pages/Home.module.scss";
import coverArt from "../public/coverArt.jpeg";
import arrowRight from "../public/arrowRight.svg";
import arrowLeft from "../public/arrowLeft.svg";
import clock from "../public/clock.svg";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Stats - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.hero}>
        <div className={styles.info}>
          <div className={styles.heroText}>
            <h1>
              Welcome to
              <br /> <span>Spotify Stats</span>
            </h1>
            <p>
              Discover all your
              <br /> favorites here!
            </p>
          </div>
          <div className={styles.heroCarrocel}>
            <Image src={coverArt} alt="cover art" height={200} width={200} />
            <Image src={coverArt} alt="cover art" height={200} width={200} />
            <Image src={coverArt} alt="cover art" height={200} width={200} />
            <Image src={coverArt} alt="cover art" height={200} width={200} />
          </div>
        </div>
        <button className={styles.login}>Login with Spotify</button>
      </div>
      <div className={styles.topSongs}>
        <div className={styles.topSongsImage}>
          <Image src={coverArt} alt="cover art" height={400} width={400} />
        </div>
        <div className={styles.topSongsArrow}>
          <Image src={arrowRight} alt="cover art" height={400} width={400} />
        </div>
        <div className={styles.topSongsText}>
          <h1>
            Discover your
            <br />
            <span>Top Songs</span>
          </h1>
        </div>
      </div>
      <div className={styles.topArtists}>
        <div className={styles.topArtistsText}>
          <h1>
            {" "}
            block; Meet your
            <br />
            <span>Top Artists</span>
          </h1>
        </div>
        <div className={styles.topArtistsArrow}>
          <Image src={arrowLeft} alt="cover art" height={400} width={400} />
        </div>

        <div className={styles.topArtistsImage}>
          <Image src={coverArt} alt="cover art" height={400} width={400} />
        </div>
      </div>
      <div className={styles.recentTracks}>
        <div className={styles.recentTracksBG}>
          <Image className={styles.clock1} src={clock} alt="clock" />
          <Image className={styles.clock2} src={clock} alt="clock" />
          <Image className={styles.clock3} src={clock} alt="clock" />
        </div>
        <div className={styles.recentTracksTxt}>
          <h1>
            See your
            <br />
            <span>Recent Tracks</span>
          </h1>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  return { props: {} };
}
