import react from "react";
import styles from "../styles/pages/RecentTracks.module.scss";
import Head from "next/head";
import Image from "next/image";
import { login, SpotifyApi, runRefreshToken } from "../src/services/spotify";
import nookies from "nookies";

export default function RecentTracks({ data, runLogin }) {
  const recentlyPlayed = data.recentlyPlayed;
  useEffect(() => {
    if (runLogin) {
      console.error("no token");
      login();
    }
  }, [runLogin]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Stats - Your Recent Tracks</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.pageTitle}>
        <h2>Recent Tracks</h2>
      </div>
      <div className={styles.songGrid}>
        {recentlyPlayed.map((track, index) => (
          <MusicCard
            image="https://i.scdn.co/image/ab67616d00001e0294e71ca5acea8203c4aa120c"
            name="Anti Hero"
          />
        ))}
      </div>
    </div>
  );
}

export async function getServerSideProps(ctx) {
  const cookies = nookies.get(ctx);

  if (cookies.access_token) {
    const data = await getLists(cookies.access_token, ctx);

    if (data.err) {
      return {
        props: { data: { recentlyPlayed: [] }, runLogin: true },
      };
    }
    console.log(data);
    return { props: { data, runLogin: false } };
  } else {
    return {
      props: { data: { recentlyPlayed: [] }, runLogin: true },
    };
  }
}

async function getLists(token, ctx) {
  SpotifyApi.setAccessToken(token);

  console.log("in");
  try {
    console.log("try 1");
    const recentlyPlayed = await SpotifyApi.getMyRecentlyPlayedTracks({
      limit: 16,
    });

    console.log(recentlyPlayed);
    return {
      recentlyPlayed: recentlyPlayed.body.items,
    };
  } catch (e) {
    console.log(e);
    if (e.body.error.message === "The access token expired") {
      const newCookies = await runRefreshToken(ctx);
      SpotifyApi.setAccessToken(newCookies.access_token);
      try {
        console.log("try 2");
        const recentlyPlayed = await SpotifyApi.getMyRecentlyPlayedTracks({
          limit: 16,
        });
        console.log(recentlyPlayed);
        return {
          recentlyPlayed: recentlyPlayed.body.items,
        };
      } catch (err) {
        console.error("second err", err);
      }
    }
  }
}

function MusicCard({ image, name }) {
  return (
    <div className={styles.gridItem}>
      <div className={styles.itemContent}>
        <div className={styles.songTitle}>{name}</div>
        <Image src={image} alt="cover art" height={200} width={200} />
      </div>
    </div>
  );
}
