import react from "react";
import Head from "next/head";
import styles from "../styles/pages/Tops.module.scss";

export default function TopArtists(props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Spotify Stats - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
